import { test, expect, Request } from '@playwright/test';

/**
 * Verifies that clicking an Approve button on a HITL confirm card in Full mode
 * posts a card_interaction payload to the prediction endpoint with the correct
 * shape (card_id, action_id, wait_id). This is the round-trip test for HITL —
 * the card rendering test only proves the UI appears; this proves a user can
 * actually resolve the HITL gate.
 */

test('clicking Approve posts card_interaction with correct payload', async ({ page }) => {
  const confirmEvent = {
    type: 'confirm_card',
    wait_id: 'wait-xyz',
    title: 'Ship it?',
    message: 'Confirm deploy',
    actions: [
      { action_id: 'approve', label: 'Approve', payload_fields: [] },
      { action_id: 'cancel', label: 'Cancel', payload_fields: [] },
    ],
  };

  await page.route('**/stream', async (route) => {
    await route.fulfill({
      status: 200,
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*',
      },
      body: `data: ${JSON.stringify(confirmEvent)}\n\n`,
    });
  });

  await page.route('**/notifications/unread*', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ notifications: [], unread_count: 0 }),
    });
  });

  // Capture the card-interaction POST. The endpoint is `${apiHost}${apiPath}/${agentId}`
  // → http://localhost:9091/chat/test-agent per our harness config.
  let capturedRequest: Request | null = null;
  await page.route('**/chat/test-agent', async (route, request) => {
    if (request.method() === 'POST') {
      capturedRequest = request;
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ ok: true }),
      });
      return;
    }
    await route.continue();
  });

  await page.goto('/test-full-agui.html');

  const host = page.locator('flowise-fullchatbot');
  const approve = host.getByRole('button', { name: 'Approve' });
  await expect(approve).toBeVisible({ timeout: 10_000 });

  await approve.click();

  await expect.poll(() => capturedRequest !== null, { timeout: 5_000 }).toBe(true);

  const body = capturedRequest!.postDataJSON();
  expect(body).toMatchObject({
    question: '',
    card_interaction: {
      card_id: expect.any(String),
      action_id: 'approve',
      wait_id: 'wait-xyz',
      payload: {},
    },
  });
  // chatId should be set (generated by useAgUiStream internally — non-empty).
  expect(typeof body.chatId).toBe('string');
  expect(body.chatId.length).toBeGreaterThan(0);
});
